import { SEVERITIES, type Severity } from '../config/schema.js';
import type { DriftReport, Evidence, Finding } from './schema.js';

export const REPORT_FILE = 'kairos-report.md';

const ICON: Record<Severity, string> = { high: '🔴', medium: '🟠', low: '🟡' };

export const severityRank = (s: Severity): number => SEVERITIES.indexOf(s);

/** Findings that reach `failOn` and so fail the check. */
export const blocking = (findings: Finding[], failOn: Severity): Finding[] =>
  findings.filter((f) => severityRank(f.severity) >= severityRank(failOn));

/** Highest severity first, then reply order. */
export const sortFindings = (findings: Finding[]): Finding[] =>
  findings
    .map((f, i) => ({ f, i }))
    .sort((a, b) => severityRank(b.f.severity) - severityRank(a.f.severity) || a.i - b.i)
    .map(({ f }) => f);

export const location = (e: Evidence): string =>
  e.lines[0] === e.lines[1] ? `${e.file}:${e.lines[0]}` : `${e.file}:${e.lines[0]}-${e.lines[1]}`;

/** Escapes text for a single Markdown table cell. */
const cell = (s: string): string => s.replace(/\|/g, '\\|').replace(/\s*\n\s*/g, ' ');

function fenced(e: Evidence): string {
  const longest = Math.max(2, ...(e.excerpt.match(/`+/g) ?? []).map((m) => m.length));
  const fence = '`'.repeat(longest + 1);
  return `${fence}\n${e.excerpt.replace(/\n+$/, '')}\n${fence}`;
}

function renderFinding(f: Finding): string {
  const out = [
    `### ${ICON[f.severity]} ${f.id} · ${f.title}`,
    `**${f.type}** · severity **${f.severity}** · confidence ${f.confidence.toFixed(2)} · source of truth: **${f.truth}**`,
    '',
    f.explanation,
    '',
    `**Code** \`${location(f.code)}\``,
    fenced(f.code),
  ];
  if (f.intent) out.push('', `**Intent** \`${location(f.intent)}\``, fenced(f.intent));
  out.push('', `**Proposal** (\`${f.proposal.action}\`): ${f.proposal.summary}`);
  out.push('', `Fix: \`kairos fix --id ${f.id}\``);
  return out.join('\n');
}

/** The Markdown report: also posted as the PR comment. */
export function renderMarkdown(report: DriftReport, opts: { failOn: Severity }): string {
  const findings = sortFindings(report.findings);
  const failing = blocking(findings, opts.failOn).length;
  const status =
    findings.length === 0
      ? '✅ **No drift found.**'
      : failing > 0
        ? `❌ **${findings.length} finding(s)**, ${failing} at or above \`${opts.failOn}\`.`
        : `⚠️ **${findings.length} finding(s)**, none at or above \`${opts.failOn}\`.`;
  const cost = report.cost?.bobcoins;
  const meta = [
    `Run \`${report.runId}\``,
    `\`${report.base}...${report.head.slice(0, 7)}\``,
    ...(cost === undefined ? [] : [`${cost} Bobcoins`]),
  ].join(' · ');

  const out = ['## Kairos drift report', '', status, '', report.summary, '', meta];
  if (findings.length > 0) {
    out.push('', '| ID | Severity | Type | Title | Code |', '|---|---|---|---|---|');
    for (const f of findings) {
      out.push(
        `| ${f.id} | ${ICON[f.severity]} ${f.severity} | ${f.type} | ${cell(f.title)} | \`${location(f.code)}\` |`,
      );
    }
    for (const f of findings) out.push('', renderFinding(f));
  }
  out.push('', '<sub>Generated by Kairos, powered by IBM Bob.</sub>', '');
  return out.join('\n');
}

/** A compact plain-text table for the terminal. */
export function renderSummary(report: DriftReport, opts: { failOn: Severity }): string {
  const findings = sortFindings(report.findings);
  const lines = [report.summary];
  if (findings.length > 0) {
    const rows = findings.map((f) => [f.id, f.severity, f.type, location(f.code), f.title]);
    const widths = [0, 1, 2, 3].map((c) => Math.max(...rows.map((r) => r[c]!.length)));
    lines.push('');
    for (const r of rows) lines.push(r.map((v, c) => (c < 4 ? v.padEnd(widths[c]!) : v)).join('  '));
  }
  const failing = blocking(findings, opts.failOn).length;
  lines.push(
    '',
    findings.length === 0
      ? 'No drift found.'
      : `${findings.length} finding(s), ${failing} at or above ${opts.failOn}.`,
  );
  return lines.join('\n');
}
